### ISSUE TITLE
头像失效

### ISSUE THREAD

**Issue by liangchuxin** [YunYouJun/friends#75]
大佬这个头像地址失效啦
https://cdn.jsdelivr.net/gh/YunYouJun/yunyoujun.github.io/images/avatar.jpg

**Comment by YunYouJun** [comment]
jsdelivr 国内挂了…… 换成 `https://fastly.jsdelivr.net/gh/YunYouJun/yunyoujun.github.io/images/avatar.jpg` 可以。

**Comment by YunYouJun** [comment]
https://www.yunyoujun.cn/images/avatar.jpg

**Comment by YunYouJun** [comment]
感谢反馈。
